// front-react/static/components/project_details.js
"use client";

import * as React from "react";
import {StringField} from "./form_components";
import fire from './event_bus'
import * as api from "./api"
import {Button, Card} from "react-bootstrap";

let _updateCurrentProjectName = (_) => {
}

const ProjectButtons = () => {

    function _projectUpdate() {
        let p_id = _currentProject.p_id
        let json = JSON.stringify(vars.currentProject)
        api.putJson200("api/projects/" + p_id, json, () => {
            fire.fetchProjects();
        })
    }

    function _projectDelete() {
        let p_id = _currentProject.p_id
        api.delete204(`api/projects/${p_id}`, () => {
            fire.setVisibleProjectDetails(false)
            fire.fetchProjects();
        })
    }

    return (
        <table className="controls">
            <tbody>
            <tr>
                <td id="currentProjectName">
                    <StringField onChange={v => {
                        _currentProject.p_name = v
                    }} saveUpdater={(updater) => {
                        _updateCurrentProjectName = updater
                    }}/>
                </td>
                <td className="w1">
                    <Button variant={"secondary"} className={"opacity-50"}
                            onClick={() => _projectUpdate()}
                    >
                        &#x2713;
                    </Button>
                </td>
                <td className="w1">
                    <Button variant={"secondary"} className={"opacity-50"}
                            onClick={() => _projectDelete()}
                    >
                        x
                    </Button>
                </td>
                <td className="w1">
                    <Button variant={"secondary"} className={"opacity-50"}
                            onClick={() => fire.setVisibleProjectDetails(false)}
                    >
                        &lt;
                    </Button>
                </td>
            </tr>
            </tbody>
        </table>
    )
}

let _updateProjectTasks = (_) => {
}

const ProjectTasks = () => {

    const [data, setData] = React.useState([])

    _updateProjectTasks = setData

    return <table className="section">
        <thead>
        <tr>
            <th className="w1">Date</th>
            <th>Subject</th>
            <th className="w1">Priority</th>
        </tr>
        </thead>
        <tbody>
        {
            data.map((task, index) => {
                    return (
                        <tr key={index}>
                            <td className="w1 nowrap">
                                {task.t_date}
                            </td>
                            <td onClick={() => fire.fetchTask(task.t_id)}>
                                <a>{task.t_subject}</a>
                            </td>
                            <td className="center">
                                {task.t_priority}
                            </td>
                        </tr>
                    )
                }
            )
        }
        </tbody>
    </table>
}

const TaskCreateButton = () => {

    function _taskCreate() {
        let p_id = _currentProject.p_id
        let json = JSON.stringify({"t_subject": _newTaskSubject})
        api.postJson201(`api/projects/${p_id}/tasks`, json, () => {
            fire.fetchProjects();
            fire.fetchProjectTasks(p_id); // update tasks count
        })
    }

    return (
        <Button variant={"secondary"} className={"opacity-50"} onClick={() => _taskCreate()}>
            +
        </Button>
    )
}

let _currentProject = {p_id: -1, p_name: ""};

fire.fetchCurrentProject = (p_id) => {
    api.getJson(`api/projects/${p_id}`, (json) => {
        if (!json) {
            fire.showServerError("failed to get project data")
            return
        }
        _currentProject = json
        _updateCurrentProjectName(_currentProject.p_name)
    })
}

fire.fetchProjectTasks = (p_id) => {
    api.getJsonArray(`api/projects/${p_id}/tasks`, (arr) => {
        fire.setVisibleProjectDetails(true)
        if (arr) {
            _updateProjectTasks(arr)
        }
    })
}

let _newTaskSubject = ""

export const PaneProjectDetails = () => {

    React.useEffect(() => {

    }, [])

    return <>
        <Card className={"bg-white rounded-3 mb-3"}>
            <Card.Body>

                <table>
                    <tbody>
                    <tr>
                        <td id="projectActions">
                            <ProjectButtons/>
                        </td>
                    </tr>
                    <tr>
                        <td id="tasks">
                            <ProjectTasks/>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table className="controls">
                                <tbody>
                                <tr>
                                    <td id="newTaskSubject">
                                        <StringField onChange={v =>
                                            _newTaskSubject = v
                                        }/>
                                    </td>
                                    <td className="w1" id="taskCreate">
                                        <TaskCreateButton/>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </Card.Body>
        </Card>

    </>
}

// front-vue/static/components/project_details.vue
<script>
import fire from "./event_bus";
import {delete204, getJson, getJsonArray, postJson201, putJson200} from "./api";

const NO_PROJECT = {"p_id": -1, "p_name": null, "p_tasks_count": -1}
const TASK = {"t_id": -1, "t_date": null, "t_subject": null, "t_priority": -1}

export default {
  data() {
    return {
      current_project: NO_PROJECT,
      tasks: [TASK],
      t_subject: null,
      show_project_details: false,
    }
  },
  created() {
    fire.hideProjectDetails = this.hideProjectDetails;
    fire.renderProjectDetails = this.renderProjectDetails;
    fire.renderProjectTasks = this.renderProjectTasks;
  },
  methods: {
    hideProjectDetails() {
      fire.hideTaskDetails()
      this.show_project_details = false
    },
    renderProjectDetails(p_id) {
      this.renderCurrentProject(p_id)
      this.renderProjectTasks(p_id)
      this.show_project_details = true
    },
    renderCurrentProject(p_id) {
      getJson("api/projects/" + p_id, (json) => {
        this.current_project = json
      })
    },
    renderProjectTasks(p_id) {
      getJsonArray("api/projects/" + p_id + "/tasks", (arr) => {
        this.tasks = arr
      })
    },
    projectUpdate() {
      let p_id = this.current_project.p_id
      let json = JSON.stringify(this.current_project)
      putJson200("api/projects/" + p_id, json, () => {
        fire.renderProjects();
      })
    },
    projectDelete() {
      let p_id = this.current_project.p_id
      delete204("api/projects/" + p_id, () => {
        this.hideProjectDetails()
        fire.renderProjects();
      })
    },
    taskCreate() {
      let p_id = this.current_project.p_id
      let json = JSON.stringify({"t_subject": this.t_subject})
      postJson201("api/projects/" + p_id + "/tasks", json, () => {
        fire.renderProjects(); // update tasks count
        this.renderProjectDetails(p_id);
      })
    },
    renderTaskDetails(t_id) {
      // this.$root.renderTaskDetails(t_id);
      fire.renderTaskDetails(t_id)
    }
  }
}
</script>

<template>
  <div class="card" v-if="show_project_details">
  <table>
    <tr>
      <td>
        <table class="controls">
          <tr>
            <td>
              <label>
                <input type="text" class="project-header" v-model="current_project.p_name"/>
              </label>
            </td>
            <td class="w1">
              <a href="#" @click="projectUpdate()">
                <input type="button" value="✓"/>
              </a>
            </td>
            <td class="w1">
              <a href="#" @click="projectDelete()">
                <input type="button" value="x"/>
              </a>
            </td>
            <td class="w1">
              <a href="#" @click="hideProjectDetails()">
                <input type="button" value="&lt;"/>
              </a>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td>
        <table class="section">
          <tr>
            <th>Date</th>
            <th>Subject</th>
            <th>Priority</th>
          </tr>
          <tr v-for="t in tasks">
            <td>
              {{ t.t_date }}
            </td>
            <td>
              <a href="#" @click="renderTaskDetails(t.t_id)">
                {{ t.t_subject }}
              </a>
            </td>
            <td style="text-align: center;">
              {{ t.t_priority }}
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td>
        <table class="controls">
          <tr>
            <td>
              <label>
                <input type="text" v-model="t_subject"/>
              </label>
            </td>
            <td class="w1">
              <a href="#" @click="taskCreate()">
                <input type="button" value="+"/>
              </a>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
  </div>
</template>

<style scoped>

</style>
