// front-vue/static/components/whoiam.vue
<script>
import {version} from "vue";

import fire from "./event_bus";
import {getText} from "./api";

export default {
  data() {
    return {
      value: "",
      is_sqlx: false
    }
  },
  created() {
    fire.renderWhoIAm = this.renderWhoIAm
  },
  methods: {
    renderWhoIAm() {
      getText('api/whoiam', (text) => {
        if (!text) {
          return
        }
        if (text.includes('sqlx')) {
          this.is_sqlx = true
        }
        this.value = text + ", npm, vue " + version
        document.title = 'SDM Todo, Vue ' + version
      })
    },
  }
}
</script>

<template>
  <div>
    {{ value }}<span v-if="is_sqlx">, <a href="swagger/index.html">swagger</a></span>
  </div>
</template>

<style>

</style>

// front-react/static/components/whoiam.js
"use client";

import * as React from "react";
import * as api from "./api"
import {RawHtml} from "./raw_html"


export const WhoIAm = () => {

    const [who, setWho] = React.useState('')

    React.useEffect(() => {
        fetchWhoIAm()
    }, [])
    
    function fetchWhoIAm() {
        api.getText('api/whoiam', (text) => {
            if (!text) {
                return
            }
            if (text.includes('sqlx')) {
                text += ', <a target="_blank" href="swagger/index.html">swagger</a>'
            }
            text += ", npm, react " + React.version

            setWho(text)
        })
    }

    return (
        <RawHtml rawHtml={who}/>
    )
}
